FROM node:22-alpine AS build

WORKDIR /app
RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/web/package.json ./apps/web/package.json
COPY packages/api-client/package.json ./packages/api-client/package.json
RUN pnpm install --filter @wherehouse/web... --frozen-lockfile

COPY apps/web ./apps/web
COPY packages/api-client ./packages/api-client
RUN pnpm --filter @wherehouse/web build

FROM nginx:stable-trixie
COPY deploy/docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/web/dist /usr/share/nginx/html
