import type { OverviewInventory } from '../dashboard/useOverviewInventory'
import type { Item } from '@wherehouse/api-client'
import { Check, ClipboardList, Pencil } from 'lucide-react'
import { useState } from 'react'

import { ItemDetailsModal, itemLocation } from './ItemsView'

export function CompanionReviewQueue({ inventory, itemIds, onClose, onReviewed, onUpdated, token }: { inventory: OverviewInventory; itemIds: string[]; onClose: () => void; onReviewed: (itemId: string) => void; onUpdated: (item: Item) => void; token: string }) {
  const [reviewing, setReviewing] = useState<Item | null>(null)
  const items = itemIds.map((id) => inventory.items.find((item) => item.id === id)).filter((item): item is Item => Boolean(item))
  if (reviewing) return <ItemDetailsModal areas={inventory.areas} containerPlacements={inventory.containerPlacements} containers={inventory.containers} item={reviewing} locationLabel={itemLocation(inventory.itemPlacements.find((entry) => entry.item_id === reviewing.id), inventory.areas, inventory.zones, inventory.containers, inventory.containerPlacements)} onClose={() => { onReviewed(reviewing.id); setReviewing(null) }} onUpdated={(item) => { setReviewing(item); onUpdated(item) }} placement={inventory.itemPlacements.find((entry) => entry.item_id === reviewing.id)} token={token} zones={inventory.zones} />
  return <div className="dialog-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section aria-labelledby="review-queue-title" aria-modal="true" className="location-dialog review-queue-dialog" role="dialog"><div className="dialog-heading"><div><p className="eyebrow">Companion capture</p><h2 id="review-queue-title">Review new items</h2><p>{itemIds.length} {itemIds.length === 1 ? 'item needs' : 'items need'} review</p></div><button aria-label="Close review queue" onClick={onClose}>×</button></div><div className="review-queue-list">{items.map((item) => <article key={item.id}><span className="review-item-icon"><ClipboardList aria-hidden="true" /></span><span><strong>{item.name}</strong><small>{item.code} · {itemLocation(inventory.itemPlacements.find((entry) => entry.item_id === item.id), inventory.areas, inventory.zones, inventory.containers, inventory.containerPlacements)}</small></span><button className="secondary-action" onClick={() => setReviewing(item)}><Pencil aria-hidden="true" /> Review</button><button aria-label={`Mark ${item.name} reviewed`} className="review-done" onClick={() => onReviewed(item.id)} title="Mark reviewed"><Check aria-hidden="true" /></button></article>)}{!items.length && inventory.loading ? <p className="review-loading">Loading new items…</p> : null}</div><div className="dialog-actions"><button className="secondary-action" onClick={onClose}>Review later</button></div></section></div>
}
