import { ArrowRightLeft, PackagePlus, QrCode, RefreshCw, Search } from 'lucide-react-native'
import { Pressable, Text, View } from 'react-native'

import type { CachedInventory } from '../services/inventory'
import type { PairedServer } from '../services/pairing'
import { styles } from '../theme/styles'

export function HomeScreen({ error, inventory, onBrowse, onForget, onRefresh, onScan, server, syncing }: { error: string | null; inventory: CachedInventory; onBrowse: () => void; onForget: () => void; onRefresh: () => void; onScan: () => void; server: PairedServer; syncing: boolean }) {
  return <View style={styles.card}><View style={styles.cardHeaderRow}><View><Text style={styles.eyebrow}>Connected household</Text><Text style={styles.cardTitle}>{server.instanceName}</Text></View><Pressable accessibilityLabel="Sync inventory" disabled={syncing} onPress={onRefresh} style={styles.refreshButton}><RefreshCw color="#4f46e5" size={18} /></Pressable></View><Text style={styles.description}>{inventory.areas.length} areas · {inventory.containers.length} containers{inventory.syncedAt ? ` · Synced ${new Date(inventory.syncedAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}` : ''}</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.actionGrid}><Pressable onPress={onScan} style={styles.actionTile}><QrCode color="#4f46e5" size={21} /><Text style={styles.actionLabel}>Scan</Text><Text style={styles.actionMeta}>Find a container</Text></Pressable><View style={styles.actionTile}><PackagePlus color="#4f46e5" size={21} /><Text style={styles.actionLabel}>Add item</Text><Text style={styles.actionMeta}>Coming next</Text></View><Pressable onPress={onBrowse} style={styles.actionTile}><Search color="#4f46e5" size={21} /><Text style={styles.actionLabel}>Browse</Text><Text style={styles.actionMeta}>Areas and containers</Text></Pressable><View style={styles.actionTile}><ArrowRightLeft color="#4f46e5" size={21} /><Text style={styles.actionLabel}>Transfer</Text><Text style={styles.actionMeta}>Coming next</Text></View></View><Pressable style={styles.secondaryButton} onPress={onForget}><Text style={styles.secondaryButtonText}>Forget this server</Text></Pressable></View>
}
