import { ArrowRightLeft, PackagePlus, QrCode, Radio, RefreshCw, Search } from 'lucide-react-native'
import { Pressable, Text, View } from 'react-native'

import type { CachedInventory } from '../services/inventory'
import type { PairedServer } from '../services/pairing'
import { styles } from '../theme/styles'

export function HomeScreen({ error, inventory, onAddItem, onBrowse, onForget, onNfc, onRefresh, onScan, pendingCount, server, syncing }: { error: string | null; inventory: CachedInventory; onAddItem: () => void; onBrowse: () => void; onForget: () => void; onNfc: () => void; onRefresh: () => void; onScan: () => void; pendingCount: number; server: PairedServer; syncing: boolean }) {
  return <View style={styles.card}><View style={styles.cardHeaderRow}><View><Text style={styles.eyebrow}>Connected household</Text><Text style={styles.cardTitle}>{server.instanceName}</Text></View><Pressable accessibilityLabel="Sync inventory" disabled={syncing} onPress={onRefresh} style={styles.refreshButton}><RefreshCw color="#4f46e5" size={18} /></Pressable></View><Text style={styles.description}>{inventory.areas.length} areas · {inventory.containers.length} containers{inventory.syncedAt ? ` · Synced ${new Date(inventory.syncedAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}` : ''}{pendingCount ? ` · ${pendingCount} pending` : ''}</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable onPress={onAddItem} style={styles.prominentAddButton}><PackagePlus color="#fff" size={22} /><View><Text style={styles.prominentAddTitle}>Add item</Text><Text style={styles.prominentAddMeta}>Photo, name, location</Text></View></Pressable><View style={styles.actionGrid}><Pressable onPress={onScan} style={styles.actionTile}><QrCode color="#4f46e5" size={21} /><Text style={styles.actionLabel}>Scan QR</Text><Text style={styles.actionMeta}>Identify anything</Text></Pressable><Pressable onPress={onNfc} style={styles.actionTile}><Radio color="#4f46e5" size={21} /><Text style={styles.actionLabel}>Tap NFC</Text><Text style={styles.actionMeta}>Identify anything</Text></Pressable><Pressable onPress={onBrowse} style={styles.actionTile}><Search color="#4f46e5" size={21} /><Text style={styles.actionLabel}>Browse</Text><Text style={styles.actionMeta}>Inventory</Text></Pressable></View><Pressable style={styles.secondaryButton} onPress={onForget}><Text style={styles.secondaryButtonText}>Forget this server</Text></Pressable></View>
}
