device:
  layer: rpi4
  hostname: wherehouse
  storage_type: sd
image:
  layer: image-rpios
  name: wherehouse-pi4
  compression: none
  root_part_size: 800%
layer:
  base: trixie-minbase
  appliance: wherehouse-appliance
