import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#fff' },
  screen: { flex: 1, backgroundColor: '#f6f7fb' },
  content: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 24, paddingBottom: 32 },
  brandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  brandLockup: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  brandMark: { width: 30, height: 30, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#172554' },
  brand: { color: '#172554', fontSize: 18, fontWeight: '800' },
  syncPill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 6, paddingHorizontal: 9, borderRadius: 20, backgroundColor: '#e9f8ef' },
  syncDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#239b56' },
  syncText: { color: '#167443', fontSize: 11, fontWeight: '700' },
  title: { marginTop: 28, fontSize: 38, lineHeight: 43, fontWeight: '800', letterSpacing: -1.5, color: '#101828' },
  subtitle: { marginTop: 8, maxWidth: 340, color: '#667085', fontSize: 16, lineHeight: 23 },
  activity: { marginTop: 40 },
  card: { marginTop: 24, padding: 20, borderWidth: 1, borderColor: '#e1e6ef', borderRadius: 14, backgroundColor: '#fff' },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  refreshButton: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#e1e6ef', borderRadius: 9, backgroundColor: '#f8f9fc' },
  eyebrow: { marginBottom: 8, color: '#4f46e5', fontSize: 11, fontWeight: '800', letterSpacing: 1.2, textTransform: 'uppercase' },
  cardTitle: { color: '#101828', fontSize: 21, fontWeight: '800' },
  description: { marginTop: 8, fontSize: 15, lineHeight: 22, color: '#667085' },
  input: { marginTop: 18, padding: 13, borderWidth: 1, borderColor: '#cfd5df', borderRadius: 10, backgroundColor: '#fff' },
  error: { marginTop: 10, color: '#b42318' },
  button: { marginTop: 10, padding: 14, borderRadius: 10, backgroundColor: '#172554', alignItems: 'center' },
  buttonDisabled: { opacity: 0.45 },
  buttonText: { color: '#fff', fontWeight: '700' },
  secondaryButton: { marginTop: 20, paddingVertical: 10 },
  secondaryButtonText: { color: '#667085', fontWeight: '700' },
  scanButton: { marginTop: 16, padding: 14, borderRadius: 10, backgroundColor: '#239b56', alignItems: 'center' },
  scanButtonText: { color: '#fff', fontWeight: '800' },
  buttonContent: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  actionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 20 },
  actionTile: { flexGrow: 1, flexBasis: '46%', minHeight: 96, padding: 13, borderWidth: 1, borderColor: '#e4e7ec', borderRadius: 11, backgroundColor: '#fafbfc' },
  actionLabel: { marginTop: 8, color: '#101828', fontSize: 14, fontWeight: '800' },
  actionMeta: { marginTop: 2, color: '#98a2b3', fontSize: 10 },
  selectedContainerCard: { marginTop: 14, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#c7d2fe', borderRadius: 11, padding: 12, backgroundColor: '#f3f4ff' },
  containerIcon: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: '#e8eaff' },
  containerCopy: { flex: 1, minWidth: 0 },
  containerName: { color: '#101828', fontSize: 14, fontWeight: '800' },
  containerMeta: { marginTop: 3, color: '#667085', fontSize: 11, textTransform: 'capitalize' },
  clearText: { color: '#4f46e5', fontSize: 11, fontWeight: '700' },
  areaSection: { marginTop: 16, overflow: 'hidden', borderWidth: 1, borderColor: '#e4e7ec', borderRadius: 11 },
  areaHeading: { flexDirection: 'row', alignItems: 'center', gap: 9, padding: 12, backgroundColor: '#f8f9fc' },
  areaName: { color: '#101828', fontSize: 14, fontWeight: '800' },
  areaMeta: { marginTop: 2, color: '#98a2b3', fontSize: 10 },
  containerRow: { flexDirection: 'row', alignItems: 'center', gap: 10, borderTopWidth: 1, borderTopColor: '#e4e7ec', padding: 12, backgroundColor: '#fff' },
  emptyInventory: { paddingVertical: 30, color: '#667085', fontSize: 13, lineHeight: 20, textAlign: 'center' },
  bottomNav: { minHeight: 66, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', borderTopWidth: 1, borderTopColor: '#e4e7ec', paddingTop: 8, paddingBottom: 6, paddingHorizontal: 12, backgroundColor: '#fff', shadowColor: '#101828', shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: -4 }, elevation: 8 },
  navTab: { flex: 1, minWidth: 54, alignItems: 'center', justifyContent: 'center', gap: 3 },
  navLabel: { color: '#667085', fontSize: 10 },
  navLabelActive: { color: '#4f46e5', fontSize: 10, fontWeight: '700' },
  scanTab: { width: 52, height: 52, marginHorizontal: 12, marginTop: -32, borderWidth: 4, borderColor: '#fff', borderRadius: 26, alignItems: 'center', justifyContent: 'center', backgroundColor: '#239b56', shadowColor: '#101828', shadowOpacity: 0.2, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 10 },
  scannerScreen: { flex: 1, backgroundColor: '#07120c' },
  scannerCamera: { ...StyleSheet.absoluteFillObject },
  scannerOverlay: { flex: 1, justifyContent: 'space-between', padding: 24, backgroundColor: 'rgba(4, 15, 9, 0.28)' },
  scannerHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  scannerTitle: { color: '#fff', fontSize: 20, fontWeight: '800' },
  closeButton: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, backgroundColor: 'rgba(0, 0, 0, 0.45)' },
  closeButtonText: { color: '#fff', fontWeight: '700' },
  finder: { alignSelf: 'center', width: 260, height: 260, borderWidth: 3, borderColor: '#4ade80', borderRadius: 24, backgroundColor: 'transparent' },
  scannerHelp: { alignSelf: 'center', maxWidth: 300, color: '#fff', fontSize: 16, lineHeight: 23, textAlign: 'center', fontWeight: '600' },
})
