import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#fff' },
  screen: { flex: 1, backgroundColor: '#f6f7fb' },
  content: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 24, paddingBottom: 32 },
  brandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  brandLogo: { width: 145, height: 48 },
  syncPill: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 6, paddingHorizontal: 9, borderRadius: 20, backgroundColor: '#e9f8ef' },
  syncDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#239b56' },
  syncText: { color: '#167443', fontSize: 11, fontWeight: '700' },
  title: { marginTop: 28, fontSize: 38, lineHeight: 43, fontWeight: '800', letterSpacing: -1.5, color: '#101828' },
  subtitle: { marginTop: 8, maxWidth: 340, color: '#667085', fontSize: 16, lineHeight: 23 },
  activity: { marginTop: 40 },
  card: { marginTop: 24, padding: 20, borderWidth: 1, borderColor: '#e1e6ef', borderRadius: 14, backgroundColor: '#fff' },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  refreshButton: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#e1e6ef', borderRadius: 9, backgroundColor: '#f8f9fc' },
  eyebrow: { marginBottom: 8, color: '#4f46e5', fontSize: 11, fontWeight: '800', letterSpacing: 1.2, textTransform: 'uppercase' },
  cardTitle: { color: '#101828', fontSize: 21, fontWeight: '800' },
  description: { marginTop: 8, fontSize: 15, lineHeight: 22, color: '#667085' },
  input: { marginTop: 18, padding: 13, borderWidth: 1, borderColor: '#cfd5df', borderRadius: 10, backgroundColor: '#fff' },
  error: { marginTop: 10, color: '#b42318' },
  button: { marginTop: 10, padding: 14, borderRadius: 10, backgroundColor: '#172554', alignItems: 'center' },
  buttonDisabled: { opacity: 0.45 },
  buttonText: { color: '#fff', fontWeight: '700' },
  secondaryButton: { marginTop: 20, paddingVertical: 10 },
  secondaryButtonText: { color: '#667085', fontWeight: '700' },
  scanButton: { marginTop: 16, padding: 14, borderRadius: 10, backgroundColor: '#239b56', alignItems: 'center' },
  scanButtonText: { color: '#fff', fontWeight: '800' },
  buttonContent: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  actionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 20 },
  actionTile: { flexGrow: 1, flexBasis: '46%', minHeight: 96, padding: 13, borderWidth: 1, borderColor: '#e4e7ec', borderRadius: 11, backgroundColor: '#fafbfc' },
  actionLabel: { marginTop: 8, color: '#101828', fontSize: 14, fontWeight: '800' },
  actionMeta: { marginTop: 2, color: '#98a2b3', fontSize: 10 },
  prominentAddButton: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 18, borderRadius: 12, paddingHorizontal: 18, backgroundColor: '#4f46e5' },
  prominentAddTitle: { color: '#fff', fontSize: 16, fontWeight: '800' },
  prominentAddMeta: { marginTop: 2, color: '#dfe3ff', fontSize: 11 },
  addToContainerButton: { minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 10, borderRadius: 10, backgroundColor: '#4f46e5' },
  addToContainerText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  containerIcon: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: '#e8eaff' },
  containerCopy: { flex: 1, minWidth: 0 },
  containerName: { color: '#101828', fontSize: 14, fontWeight: '800' },
  containerMeta: { marginTop: 3, color: '#667085', fontSize: 11, textTransform: 'capitalize' },
  clearText: { color: '#4f46e5', fontSize: 11, fontWeight: '700' },
  areaSection: { marginTop: 16, overflow: 'hidden', borderWidth: 1, borderColor: '#e4e7ec', borderRadius: 11 },
  areaHeading: { flexDirection: 'row', alignItems: 'center', gap: 9, padding: 12, backgroundColor: '#f8f9fc' },
  areaName: { color: '#101828', fontSize: 14, fontWeight: '800' },
  areaMeta: { marginTop: 2, color: '#98a2b3', fontSize: 10 },
  containerRow: { flexDirection: 'row', alignItems: 'center', gap: 10, borderTopWidth: 1, borderTopColor: '#e4e7ec', padding: 12, backgroundColor: '#fff' },
  emptyInventory: { paddingVertical: 30, color: '#667085', fontSize: 13, lineHeight: 20, textAlign: 'center' },
  locationPanel: { marginTop: 22, padding: 18, borderWidth: 1, borderColor: '#e1e6ef', borderRadius: 14, backgroundColor: '#fff' },
  locationHeadingCopy: { flex: 1, minWidth: 0 },
  locationHeading: { color: '#101828', fontSize: 24, fontWeight: '800' },
  locationToolbar: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginTop: 14, borderTopWidth: 1, borderTopColor: '#edf0f5', paddingTop: 12 },
  locationToolButton: { maxWidth: '52%', flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 6 },
  locationToolText: { color: '#4f46e5', fontSize: 11, fontWeight: '800' },
  locationSummary: { flexDirection: 'row', alignItems: 'center', gap: 20, marginTop: 8, borderRadius: 11, padding: 14, backgroundColor: '#f8f9fc' },
  locationSummaryCount: { color: '#101828', fontSize: 20, fontWeight: '800' },
  locationSummaryLabel: { marginTop: 1, color: '#667085', fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  locationSummaryDivider: { width: 1, alignSelf: 'stretch', backgroundColor: '#dfe3ec' },
  locationGroup: { marginTop: 18, overflow: 'hidden', borderWidth: 1, borderColor: '#e4e7ec', borderRadius: 11 },
  locationGroupHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 9, paddingHorizontal: 12, backgroundColor: '#f8f9fc' },
  locationGroupTitle: { color: '#344054', fontSize: 11, fontWeight: '800', letterSpacing: 0.7, textTransform: 'uppercase' },
  locationGroupCount: { minWidth: 22, overflow: 'hidden', borderRadius: 11, paddingVertical: 2, paddingHorizontal: 6, color: '#4338ca', fontSize: 10, fontWeight: '800', textAlign: 'center', backgroundColor: '#eef2ff' },
  locationContentRow: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 11, borderTopWidth: 1, borderTopColor: '#edf0f5', padding: 11, backgroundColor: '#fff' },
  locationRowIcon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: '#e8eaff' },
  locationItemIcon: { backgroundColor: '#eef7f1' },
  locationEmpty: { alignItems: 'center', marginTop: 18, borderRadius: 12, padding: 24, backgroundColor: '#f8f9fc' },
  locationEmptyTitle: { marginTop: 10, color: '#344054', fontSize: 16, fontWeight: '800' },
  locationNfcButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  locationSelectorBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(16, 24, 40, 0.45)' },
  locationSelectorDismiss: { flex: 1 },
  locationSelectorSheet: { maxHeight: '82%', borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 18, paddingTop: 18, paddingBottom: 34, backgroundColor: '#fff' },
  locationSelectorHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 14 },
  locationSelectorTitle: { color: '#101828', fontSize: 22, fontWeight: '800' },
  locationSelectorSubtitle: { marginTop: 3, color: '#667085', fontSize: 12 },
  selectorNavigation: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 12, borderTopWidth: 1, borderTopColor: '#edf0f5', paddingTop: 12 },
  selectorBackButton: { minHeight: 40, flexDirection: 'row', alignItems: 'center', gap: 3 },
  selectorChooseButton: { minHeight: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 9, paddingHorizontal: 14, backgroundColor: '#4f46e5' },
  selectorChooseText: { color: '#fff', fontSize: 12, fontWeight: '800' },
  selectorHierarchyRow: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 8, borderWidth: 1, borderColor: '#e4e7ec', borderRadius: 11, paddingHorizontal: 13, backgroundColor: '#fff' },
  bottomNav: { minHeight: 66, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', borderTopWidth: 1, borderTopColor: '#e4e7ec', paddingTop: 8, paddingBottom: 6, paddingHorizontal: 12, backgroundColor: '#fff', shadowColor: '#101828', shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: -4 }, elevation: 8 },
  navTab: { flex: 1, minWidth: 54, alignItems: 'center', justifyContent: 'center', gap: 3 },
  navLabel: { color: '#667085', fontSize: 10 },
  navLabelActive: { color: '#4f46e5', fontSize: 10, fontWeight: '700' },
  scanTab: { width: 52, height: 52, marginHorizontal: 12, marginTop: -32, borderWidth: 4, borderColor: '#fff', borderRadius: 26, alignItems: 'center', justifyContent: 'center', backgroundColor: '#239b56', shadowColor: '#101828', shadowOpacity: 0.2, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 10 },
  addItemScreen: { flex: 1, backgroundColor: '#f6f7fb' },
  addItemHeader: { borderBottomWidth: 1, borderBottomColor: '#e4e7ec', paddingHorizontal: 20, paddingTop: 18, paddingBottom: 14, backgroundColor: '#fff' },
  addItemTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 16 },
  addItemTitle: { color: '#101828', fontSize: 30, lineHeight: 34, fontWeight: '800', letterSpacing: -1 },
  addItemSubtitle: { marginTop: 3, color: '#667085', fontSize: 13 },
  closeItemButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#e4e7ec', borderRadius: 10, backgroundColor: '#f8f9fc' },
  addItemContent: { padding: 16, paddingBottom: 28 },
  photoPanel: { overflow: 'hidden', borderWidth: 1, borderColor: '#dfe3ec', borderRadius: 14, backgroundColor: '#fff' },
  photoPlaceholder: { height: 150, alignItems: 'center', justifyContent: 'center', padding: 20, backgroundColor: '#f8f9fc' },
  photoPrompt: { marginTop: 8, color: '#344054', fontSize: 15, fontWeight: '800' },
  photoHint: { marginTop: 3, color: '#98a2b3', fontSize: 11, textAlign: 'center' },
  itemPhoto: { width: '100%', height: 190, resizeMode: 'cover' },
  photoActions: { flexDirection: 'row', gap: 10, padding: 12 },
  photoButtonPrimary: { flex: 1, minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 10, backgroundColor: '#239b56' },
  photoButtonPrimaryText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  photoButton: { minWidth: 104, minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderWidth: 1, borderColor: '#d8deea', borderRadius: 10, backgroundColor: '#fff' },
  photoButtonText: { color: '#4f46e5', fontSize: 13, fontWeight: '800' },
  quickFields: { gap: 10, marginTop: 14, borderWidth: 1, borderColor: '#e1e6ef', borderRadius: 14, padding: 16, backgroundColor: '#fff' },
  fieldHeading: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  fieldLabel: { color: '#344054', fontSize: 13, fontWeight: '800' },
  fieldHint: { marginTop: 2, color: '#98a2b3', fontSize: 10 },
  optionalText: { color: '#98a2b3', fontSize: 10 },
  itemNameInput: { minHeight: 52, borderWidth: 1, borderColor: '#cfd5df', borderRadius: 10, paddingHorizontal: 14, backgroundColor: '#fff', color: '#101828', fontSize: 18, fontWeight: '700' },
  quantityRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 4 },
  quantityStepper: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#d8deea', borderRadius: 10, backgroundColor: '#fff' },
  quantityButton: { width: 44, height: 42, alignItems: 'center', justifyContent: 'center' },
  quantityValue: { minWidth: 38, color: '#101828', fontSize: 16, fontWeight: '800', textAlign: 'center' },
  locationPicker: { gap: 10, marginTop: 8, borderTopWidth: 1, borderTopColor: '#edf0f5', paddingTop: 14 },
  selectedLocation: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#c7d2fe', borderRadius: 10, paddingHorizontal: 12, backgroundColor: '#f3f4ff' },
  locationCopy: { flex: 1, minWidth: 0 },
  locationName: { color: '#101828', fontSize: 13, fontWeight: '800' },
  locationDetail: { marginTop: 2, color: '#667085', fontSize: 10 },
  changeText: { color: '#4f46e5', fontSize: 11, fontWeight: '800' },
  recentLabel: { marginBottom: 7, color: '#667085', fontSize: 10, fontWeight: '800', letterSpacing: 0.7, textTransform: 'uppercase' },
  locationChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  locationChip: { maxWidth: '48%', borderRadius: 20, paddingVertical: 8, paddingHorizontal: 11, backgroundColor: '#eef2ff' },
  locationChipText: { color: '#4338ca', fontSize: 11, fontWeight: '700' },
  locationActions: { flexDirection: 'row', gap: 8 },
  locationAction: { flex: 1, minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderWidth: 1, borderColor: '#d8deea', borderRadius: 10, backgroundColor: '#fff' },
  locationActionText: { color: '#4f46e5', fontSize: 11, fontWeight: '800' },
  locationResults: { overflow: 'hidden', borderWidth: 1, borderColor: '#e4e7ec', borderRadius: 10 },
  locationSearch: { minHeight: 44, borderBottomWidth: 1, borderBottomColor: '#e4e7ec', paddingHorizontal: 12, backgroundColor: '#f8f9fc' },
  locationResult: { minHeight: 50, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: 1, borderBottomColor: '#edf0f5', paddingHorizontal: 12, backgroundColor: '#fff' },
  optionalToggle: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12, borderWidth: 1, borderColor: '#e1e6ef', borderRadius: 11, paddingHorizontal: 14, backgroundColor: '#fff' },
  optionalToggleText: { color: '#475467', fontSize: 13, fontWeight: '800' },
  optionalFields: { gap: 10, marginTop: 8 },
  secondaryInput: { minHeight: 48, borderWidth: 1, borderColor: '#d8deea', borderRadius: 10, paddingHorizontal: 13, backgroundColor: '#fff' },
  twoInputs: { flexDirection: 'row', gap: 8 },
  flexInput: { flex: 1 },
  notesInput: { minHeight: 88, paddingTop: 12, textAlignVertical: 'top' },
  addItemFooter: { borderTopWidth: 1, borderTopColor: '#e4e7ec', padding: 12, backgroundColor: '#fff', shadowColor: '#101828', shadowOpacity: 0.08, shadowRadius: 12, shadowOffset: { width: 0, height: -4 }, elevation: 10 },
  saveButton: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, borderRadius: 12, backgroundColor: '#4f46e5' },
  saveButtonText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  saveSuccess: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28 },
  successIcon: { width: 72, height: 72, alignItems: 'center', justifyContent: 'center', borderRadius: 36, backgroundColor: '#239b56' },
  successTitle: { marginTop: 20, color: '#101828', fontSize: 28, fontWeight: '800' },
  successMessage: { maxWidth: 300, marginTop: 8, color: '#667085', fontSize: 14, lineHeight: 21, textAlign: 'center' },
  retainedLocation: { width: '100%', marginVertical: 20, borderRadius: 11, padding: 14, backgroundColor: '#eef2ff' },
  doneButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center', marginTop: 8, paddingHorizontal: 40 },
  doneButtonText: { color: '#4f46e5', fontSize: 14, fontWeight: '800' },
  itemsPanel: { marginTop: 22, overflow: 'hidden', borderWidth: 1, borderColor: '#e1e6ef', borderRadius: 14, backgroundColor: '#fff' },
  itemSearch: { flex: 1, minHeight: 50, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: 1, borderBottomColor: '#e4e7ec', paddingHorizontal: 14, backgroundColor: '#f8f9fc' },
  itemSearchInput: { flex: 1, minHeight: 48, color: '#101828' },
  itemListRow: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: 1, borderBottomColor: '#edf0f5', paddingHorizontal: 13, backgroundColor: '#fff' },
  itemListIcon: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: '#eef2ff' },
  itemListCopy: { flex: 1, minWidth: 0 },
  itemListName: { color: '#101828', fontSize: 14, fontWeight: '800' },
  itemListMeta: { marginTop: 3, color: '#667085', fontSize: 10 },
  editItemText: { color: '#4f46e5', fontSize: 11, fontWeight: '800' },
  identifierChoices: { flexDirection: 'row', gap: 6 },
  identifierChoice: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#d8deea', borderRadius: 9, backgroundColor: '#fff' },
  identifierChoiceActive: { borderColor: '#4f46e5', backgroundColor: '#eef2ff' },
  identifierText: { color: '#667085', fontSize: 11, fontWeight: '700' },
  identifierTextActive: { color: '#4338ca', fontSize: 11, fontWeight: '800' },
  scannerScreen: { flex: 1, backgroundColor: '#07120c' },
  scannerCamera: { ...StyleSheet.absoluteFillObject },
  scannerOverlay: { flex: 1, justifyContent: 'space-between', padding: 24, backgroundColor: 'rgba(4, 15, 9, 0.28)' },
  scannerHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  scannerTitle: { color: '#fff', fontSize: 20, fontWeight: '800' },
  closeButton: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, backgroundColor: 'rgba(0, 0, 0, 0.45)' },
  closeButtonText: { color: '#fff', fontWeight: '700' },
  finder: { alignSelf: 'center', width: 260, height: 260, borderWidth: 3, borderColor: '#4ade80', borderRadius: 24, backgroundColor: 'transparent' },
  scannerHelp: { alignSelf: 'center', maxWidth: 300, color: '#fff', fontSize: 16, lineHeight: 23, textAlign: 'center', fontWeight: '600' },
  quickActionBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(16, 24, 40, 0.45)' },
  quickActionSheet: { gap: 10, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 34, backgroundColor: '#fff' },
  quickActionHeading: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 6 },
  quickActionTitle: { color: '#101828', fontSize: 20, fontWeight: '800' },
  quickActionSubtitle: { marginTop: 3, color: '#667085', fontSize: 12 },
  quickActionOption: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 14, borderWidth: 1, borderColor: '#e1e6ef', borderRadius: 13, paddingHorizontal: 16, backgroundColor: '#fff' },
  quickActionOptionTitle: { color: '#101828', fontSize: 15, fontWeight: '800' },
  quickActionOptionMeta: { marginTop: 2, color: '#667085', fontSize: 11 },
})
